# Copyright (C) 2022, Gauthier Leonard
# See the file LICENSE for licensing terms.
---
avalanchego_http_host: 192.168.60.11

subnet_control_keys_threshold: 2
subnet_validators_weight: 1

create_blockchains:
  - vm: subnet-evm
    name: Subnet EVM
    aliases:
      - subnet-evm
    genesis_params:
      genesisData:
        config:
          chainId: 13213
          homesteadBlock: 0
          eip150Block: 0
          eip150Hash: "0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0"
          eip155Block: 0
          eip158Block: 0
          byzantiumBlock: 0
          constantinopleBlock: 0
          petersburgBlock: 0
          istanbulBlock: 0
          muirGlacierBlock: 0
          subnetEVMTimestamp: 0
          feeConfig:
            gasLimit: 8000000
            minBaseFee: 25000000000
            targetGas: 15000000
            baseFeeChangeDenominator: 36
            minBlockGasCost: 0
            maxBlockGasCost: 1000000
            targetBlockRate: 2
            blockGasCostStep: 200000
        alloc:
          8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC:
            balance: "0x295BE96E64066972000000"
        nonce: "0x0"
        timestamp: "0x0"
        extraData: "0x00"
        gasLimit: "0x7A1200"
        difficulty: "0x0"
        mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000"
        coinbase: "0x0000000000000000000000000000000000000000"
        number: "0x0"
        gasUsed: "0x0"
        parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000"
