networks:
  avalanchelocal:
    ipam:
      driver: default
      config:
        - subnet: 177.17.0.0/24
services:
  avalanche-local-validator01:
    image: "ash/avalanche-node-local-validator01:${AVALANCHEGO_VERSION:-1.10.9}-${AVALANCHEGO_VM_NAME:-subnet-evm}-${AVALANCHEGO_VM_VERSION:-0.5.6}"
    container_name: ash-avalanche-local-validator01
    ports:
      - "9650:9650"
      - "9651:9651"
    networks:
      avalanchelocal:
        ipv4_address: 177.17.0.11
    volumes:
      - ./data/conf/bootstrap/conf:/etc/avalanche/avalanchego/mounted-conf
  avalanche-local-validator02:
    image: "ash/avalanche-node-local-validator02:${AVALANCHEGO_VERSION:-1.10.9}-${AVALANCHEGO_VM_NAME:-subnet-evm}-${AVALANCHEGO_VM_VERSION:-0.5.6}"
    container_name: ash-avalanche-local-validator02
    ports:
      - "9652:9650"
      - "9653:9651"
    networks:
      avalanchelocal:
        ipv4_address: 177.17.0.12
    volumes:
      - ./data/conf/node/conf:/etc/avalanche/avalanchego/mounted-conf
  avalanche-local-validator03:
    image: "ash/avalanche-node-local-validator03:${AVALANCHEGO_VERSION:-1.10.9}-${AVALANCHEGO_VM_NAME:-subnet-evm}-${AVALANCHEGO_VM_VERSION:-0.5.6}"
    container_name: ash-avalanche-local-validator03
    ports:
      - "9654:9650"
      - "9655:9651"
    networks:
      avalanchelocal:
        ipv4_address: 177.17.0.13
    volumes:
      - ./data/conf/node/conf:/etc/avalanche/avalanchego/mounted-conf
  avalanche-local-validator04:
    image: "ash/avalanche-node-local-validator04:${AVALANCHEGO_VERSION:-1.10.9}-${AVALANCHEGO_VM_NAME:-subnet-evm}-${AVALANCHEGO_VM_VERSION:-0.5.6}"
    container_name: ash-avalanche-local-validator04
    ports:
      - "9656:9650"
      - "9657:9651"
    networks:
      avalanchelocal:
        ipv4_address: 177.17.0.14
    volumes:
      - ./data/conf/node/conf:/etc/avalanche/avalanchego/mounted-conf
  avalanche-local-validator05:
    image: "ash/avalanche-node-local-validator05:${AVALANCHEGO_VERSION:-1.10.9}-${AVALANCHEGO_VM_NAME:-subnet-evm}-${AVALANCHEGO_VM_VERSION:-0.5.6}"
    container_name: ash-avalanche-local-validator05
    ports:
      - "9658:9650"
      - "9659:9651"
    networks:
      avalanchelocal:
        ipv4_address: 177.17.0.15
    volumes:
      - ./data/conf/node/conf:/etc/avalanche/avalanchego/mounted-conf
